import sys
import json
import re
from pathlib import Path
import streamlit as st

sys.path.insert(0, str(Path(__file__).parent.parent))
from rag.pipeline import run_pipeline
sys.path.insert(0, str(Path(__file__).parent))
from sheets_logger import log_query


def _ensure_chroma_built():
    """Ensure precomputed_embeddings.json has texts+metadatas (needed by numpy retriever)."""
    precomputed = Path("data/extracted/precomputed_embeddings.json")
    needs_rebuild = True
    if precomputed.exists():
        import json as _json
        pre = _json.loads(precomputed.read_text())
        if "texts" in pre and "metadatas" in pre:
            print(f"Embeddings ready ({len(pre['ids'])} chunks).")
            needs_rebuild = False
    if needs_rebuild:
        print("Building embeddings index...")
        from ingest.embed_and_index import embed_and_index
        embed_and_index()
        print("Embeddings index ready.")

QUESTIONS_PATH = Path("questionnaire/questions.json")
DATA_RAW = Path("data/raw")


@st.cache_data
def load_cs1_20_meta() -> dict[str, dict]:
    """Load case metadata for all case studies (CS1 onwards)."""
    meta = {}
    if not DATA_RAW.exists():
        return meta
    for folder in DATA_RAW.iterdir():
        m = __import__("re").match(r"^(CS\d+)", folder.name)
        if m:
            meta_path = folder / "case_meta.json"
            if meta_path.exists():
                cid = m.group(1)
                meta[cid] = json.loads(meta_path.read_text())
    return meta


def load_questions() -> list[dict]:
    return json.loads(QUESTIONS_PATH.read_text())["questions"]


def _section_label(section: str) -> str:
    label = section.replace("_", " ").title()
    return label if len(label) < 60 else label[:57] + "..."


def _clean_excerpt(text: str, max_chars: int = 800) -> str:
    text = re.sub(r'^Case study:.*?\n', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^Section:.*?\n', '', text, flags=re.IGNORECASE)
    text = re.sub(r'^#{1,6}\s+', '', text, flags=re.MULTILINE)
    text = re.sub(r'\*{1,2}([^*]+)\*{1,2}', r'\1', text)
    text = re.sub(r'_{1,2}([^_]+)_{1,2}', r'\1', text)
    text = re.sub(r'^[-*_]{3,}\s*$', '', text, flags=re.MULTILINE)
    text = re.sub(r'\n{3,}', '\n\n', text).strip()
    if len(text) > max_chars:
        text = text[:max_chars].rsplit(' ', 1)[0] + ' ...'
    return text


# ── Build ChromaDB before any Streamlit calls ─────────────────────────────────
_ensure_chroma_built()

# ── Page config ───────────────────────────────────────────────────────────────
st.set_page_config(page_title="AI-Assisted Knowledge Platform for Managed Retreat", layout="wide")

# ── Session state ─────────────────────────────────────────────────────────────
if "history" not in st.session_state:
    st.session_state.history = []
if "disclaimer_accepted" not in st.session_state:
    st.session_state.disclaimer_accepted = False

# ── Disclaimer modal ──────────────────────────────────────────────────────────
if not st.session_state.disclaimer_accepted:
    st.markdown("""
    <style>
    .disclaimer-wrap {
        display: flex;
        flex-direction: column;
        align-items: center;
        max-width: 720px;
        margin: 4rem auto 0 auto;
    }
    .disclaimer-wrap h1 {
        font-size: 2rem;
        margin-bottom: 1.5rem;
        text-align: center;
    }
    .disclaimer-box {
        background: #fffff0;
        border: 1px solid #e6c84a;
        border-radius: 6px;
        padding: 1.5rem 2rem 1.5rem 2rem;
        text-align: left;
        color: #5a4a00;
        font-size: 0.95rem;
        line-height: 1.6;
        width: 100%;
    }
    /* Push the Streamlit button to sit right below the box, right-aligned */
    .disclaimer-wrap + div [data-testid="stButton"] {
        display: flex;
        justify-content: flex-end;
        max-width: 720px;
        margin: 0.75rem auto 0 auto;
    }
    </style>
    <div class="disclaimer-wrap">
        <h1>AI-Assisted Knowledge Platform for Managed Retreat</h1>
        <div class="disclaimer-box">
            <p><strong>Important Notice — Research Tool Disclaimer</strong></p>
            <p>This tool is intended to support informed decision-making by providing access to
            synthesised insights from peer-reviewed managed retreat case study literature.
            It is designed as a decision-support resource only.</p>
            <p><strong>This tool does not constitute professional planning, legal, engineering, or policy advice.</strong>
            Responses are generated by an AI system and may contain errors, omissions, or
            information that does not apply to your specific context. All outputs should be
            critically evaluated and verified against primary sources before use in any
            planning or policy process.</p>
            <p><strong>The responsibility for any decision remains entirely with the user and their organisation.</strong>
            The researchers and institutions associated with the Retreat From Risk (RFR) project
            accept no liability for decisions made on the basis of information provided by this tool.</p>
            <p>By continuing, you acknowledge that you have read and understood this notice.</p>
        </div>
    </div>
    """, unsafe_allow_html=True)
    _, btn_col = st.columns([5, 2])
    with btn_col:
        if st.button("I understand — continue to the tool", type="primary"):
            st.session_state.disclaimer_accepted = True
            st.rerun()
    st.stop()

# ── Sidebar ───────────────────────────────────────────────────────────────────
with st.sidebar:
    st.header("About You & Your Community")
    st.markdown(
        """
        **How to use this tool:**
        Answer the questions below to help tailor responses to your context.
        All questions are optional — skip any that don't apply.

        Then type your question in the main panel. The tool will search
        across real managed retreat case studies and generate a response
        grounded in evidence from similar situations.

        > 💡 **Tip:** The more specific your question, the more useful
        > the answer. Try asking about funding models, community
        > engagement strategies, or what happened in a particular
        > type of community.
        """
    )
    st.divider()

    questions = load_questions()
    answers = {}
    for q in questions:
        answer = st.selectbox(q["text"], options=["(skip)"] + q["options"], key=q["id"])
        if answer != "(skip)":
            answers[q["id"]] = answer

    st.divider()
    answered = len(answers)
    total = len(questions)
    if answered == 0:
        st.caption("No context provided — answers will be general.")
    elif answered < total:
        st.caption(f"{answered} of {total} questions answered.")
    else:
        st.caption("✓ Full context provided.")

    model_choice = "claude"

# ── Two-column layout ─────────────────────────────────────────────────────────
main_col, history_col = st.columns([2, 1], gap="large")

# ── Main panel ────────────────────────────────────────────────────────────────
with main_col:
    st.title("AI-Assisted Knowledge Platform for Managed Retreat")
    st.caption("Powered by RFR research — answers grounded in real managed retreat case studies from around the world.")

    st.subheader("Ask a question")
    st.markdown(
        "Examples: *What funding models have worked for coastal buyout programs?* · "
        "*How did communities maintain social cohesion after relocation?* · "
        "*What are the biggest barriers to managed retreat in Indigenous communities?*"
    )
    st.caption(
        "⚠️ This tool is a research aid only. Responses are AI-generated from case study literature "
        "and may contain errors or omissions. They do not constitute professional advice. "
        "All decisions remain the sole responsibility of the user."
    )
    query = st.text_area("Your question:", height=100, placeholder="Type your question about managed retreat here...")

    if st.button("Get answer", type="primary"):
        if not query.strip():
            st.warning("Please enter a question.")
        elif re.search(r"\b(what|which|list|show|how many).{0,30}case stud", query, re.I):
            # Meta question — list all case studies directly from extracted JSONs
            cs_meta = load_cs1_20_meta()
            extracted_dir = Path("data/extracted")
            all_cases = []
            for f in sorted(extracted_dir.glob("CS*.json"), key=lambda p: int(re.search(r'\d+', p.stem).group())):
                cid = f.stem
                if cid in cs_meta:
                    m = cs_meta[cid]
                    all_cases.append(f"**{cid}** — {m.get('name', cid)}, {m.get('location', '')}, {m.get('country', '')}")
                else:
                    data = json.loads(f.read_text())
                    if data:
                        loc = data[0].get("location", "")
                        country = data[0].get("country", "")
                        all_cases.append(f"**{cid}** — {loc}, {country}" if loc else f"**{cid}**")
            st.markdown("### Case Studies in the Knowledge Base")
            for line in all_cases:
                st.markdown(line)
            st.caption(f"Total: {len(all_cases)} case studies indexed.")
            chunks = []
        else:
            with st.spinner("Searching case studies and generating response..."):
                answer, chunks = run_pipeline(
                    query,
                    questionnaire_answers=answers if answers else None,
                    model=model_choice,
                    return_chunks=True,
                )

            # Save to history
            st.session_state.history.insert(0, {
                "query":   query,
                "answer":  answer,
                "chunks":  chunks,
                "context": dict(answers),
            })

            # Log to Google Sheets
            _log_err = log_query(query, answer, chunks, questionnaire_answers=answers, model=model_choice)
            if _log_err:
                st.caption(f"⚠️ Logging error (temporary debug): {_log_err}")

            st.markdown("### Response")
            st.caption(
                "⚠️ The following response is AI-generated from managed retreat research literature. "
                "It is intended to support — not replace — professional judgement. Verify findings "
                "against primary sources before use in any planning or policy process."
            )
            st.markdown(answer.replace("$", r"\$"))

            # ── Context used ──────────────────────────────────────────────
            if answers:
                with st.expander("Context used"):
                    for qid, val in answers.items():
                        q_text = next((q["text"] for q in questions if q["id"] == qid), qid)
                        st.markdown(f"**{q_text}** {val}")

            # ── Case studies used ─────────────────────────────────────────
            cs_meta = load_cs1_20_meta()

            seen_ids: set[str] = set()
            retrieved_cs = []
            for c in chunks:
                cid = c["metadata"].get("case_id", "")
                if cid in cs_meta and cid not in seen_ids:
                    seen_ids.add(cid)
                    retrieved_cs.append(c)

            mentioned_ids = {
                f"CS{n}" for n in re.findall(r'\bCS([1-9]|1[0-9]|20)\b', answer)
            }

            if retrieved_cs:
                st.markdown("---")
                st.markdown("### Case Studies Used in This Answer")
                st.caption(
                    "These are the case studies whose extracted content was retrieved "
                    "and sent to the model to generate the response above."
                )
                for chunk in retrieved_cs:
                    cid     = chunk["metadata"]["case_id"]
                    meta    = cs_meta[cid]
                    name    = meta.get("name", "") or meta.get("location", cid)
                    country = meta.get("country", "")
                    section = _section_label(chunk["metadata"].get("section", ""))
                    cited   = "✅ cited in response" if cid in mentioned_ids else "📄 used as context"

                    with st.expander(f"{cid} — {name}, {country}  {cited}"):
                        st.markdown(f"**Section retrieved:** {section}")
                        st.markdown(f"**Source:** {chunk['metadata'].get('source', '')}")
                        excerpt = _clean_excerpt(chunk["text"])
                        if len(excerpt) > 40:
                            st.markdown("**Excerpt:**")
                            st.text(excerpt)
                        else:
                            st.caption("This section contains structural metadata only — no content preview available.")

# ── History panel (right column) ──────────────────────────────────────────────
with history_col:
    st.subheader("Previous Responses")

    if not st.session_state.history:
        st.caption("Your previous answers will appear here.")
    else:
        if st.button("Clear history", type="secondary"):
            st.session_state.history = []
            st.rerun()

        for i, entry in enumerate(st.session_state.history):
            label = entry["query"][:60] + "..." if len(entry["query"]) > 60 else entry["query"]
            with st.expander(f"Q{len(st.session_state.history) - i}: {label}"):
                st.markdown(f"**Question:** {entry['query']}")
                st.divider()
                st.markdown(entry["answer"])

                if entry["context"]:
                    st.divider()
                    st.caption("Context used:")
                    for qid, val in entry["context"].items():
                        q_text = next((q["text"] for q in questions if q["id"] == qid), qid)
                        st.caption(f"• {q_text}: {val}")
